# Generated by Django 4.1.2 on 2022-10-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='jon_city',
            new_name='job_city',
        ),
    ]
